### ISSUE TITLE
br

### ISSUE THREAD

**Issue by davawen** [sabrina-aip/wage-gauge#2]
I have no idea why I even posted this issue 4 months ago, apart from an apparent envy to... gate-keep web development?? what the fuck??

**Comment by mtarek2005** [comment]
CSS can be very confusing for beginners

**Comment by davawen** [comment]
I just realized it's not really clear that this is satire, so, it is ._.

**Comment by mtarek2005** [comment]
I know it's satire but I chose to comment anyways
