### ISSUE TITLE
Question off screen on Android chrome

### ISSUE THREAD

**Issue by JohnSaff** [sabrina-aip/wage-gauge#3]
There seems to be a CSS issue with the version of this currently up, but I can't seem to repro with the version here, although there seem to be some differences between this code and what's up.
![Screenshot_20220427-013643](https://user-images.githubusercontent.com/52494104/165415631-7f5bd1a2-a6ee-499d-8950-6483c8f46ab2.jpg)

May be able to fix if I can find out how to repro with this code

**Comment by mtarek2005** [comment]
it seems completely or mostly unoptimized for mobile
